from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget

class Ui_Graphs(QWidget):
    def __init__(self):
        QWidget.__init__(self)
        self.setObjectName("Form")
        self.resize(480, 378)
        self.exampleGraphGroupBox = QtWidgets.QGroupBox(self)
        self.exampleGraphGroupBox.setGeometry(QtCore.QRect(10, 10, 451, 261))
        self.exampleGraphGroupBox.setObjectName("exampleGraphGroupBox")
        self.listWidget = QtWidgets.QListWidget(self.exampleGraphGroupBox)
        self.listWidget.setGeometry(QtCore.QRect(10, 20, 311, 231))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.btnGenerateGraph = QtWidgets.QPushButton(self.exampleGraphGroupBox)
        self.btnGenerateGraph.setGeometry(QtCore.QRect(332, 20, 111, 28))
        self.btnGenerateGraph.setObjectName("btnGenerateGraph")
        self.groupBox = QtWidgets.QGroupBox(self)
        self.groupBox.setGeometry(QtCore.QRect(10, 270, 451, 91))
        self.groupBox.setObjectName("groupBox")
        self.xAxisInput = QtWidgets.QLineEdit(self.groupBox)
        self.xAxisInput.setGeometry(QtCore.QRect(60, 20, 241, 22))
        self.xAxisInput.setObjectName("xAxisInput")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 55, 16))
        self.label_2.setObjectName("label_2")
        self.yAxisInput = QtWidgets.QLineEdit(self.groupBox)
        self.yAxisInput.setGeometry(QtCore.QRect(60, 50, 241, 21))
        self.yAxisInput.setObjectName("yAxisInput")
        self.btnGenerateCustomGraph = QtWidgets.QPushButton(self.groupBox)
        self.btnGenerateCustomGraph.setGeometry(QtCore.QRect(310, 20, 131, 28))
        self.btnGenerateCustomGraph.setObjectName("btnGenerateCustomGraph")
        self.btnViewAttributes = QtWidgets.QPushButton(self.groupBox)
        self.btnViewAttributes.setGeometry(QtCore.QRect(310, 50, 131, 28))
        self.btnViewAttributes.setObjectName("btnViewAttributes")

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.exampleGraphGroupBox.setTitle(_translate("Form", "Example graphs"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Form", "All biking distance ridden"))
        item = self.listWidget.item(1)
        item.setText(_translate("Form", "Sum of biking duration for competitor"))
        item = self.listWidget.item(2)
        item.setText(_translate("Form", "Altitude vs calories"))
        item = self.listWidget.item(3)
        item.setText(_translate("Form", "Activity type vs calories"))
        item = self.listWidget.item(4)
        item.setText(_translate("Form", "Map with identified hills"))
        item = self.listWidget.item(5)
        item.setText(_translate("Form", "Map with identified intervals"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.btnGenerateGraph.setText(_translate("Form", "Generate graph"))
        self.groupBox.setTitle(_translate("Form", "Custom graph"))
        self.label.setText(_translate("Form", "X axis"))
        self.label_2.setText(_translate("Form", "Y axis"))
        self.btnGenerateCustomGraph.setText(_translate("Form", "Generate graph"))
        self.btnViewAttributes.setText(_translate("Form", "View data attributes"))
